Repository Team-Silver-Sphere/SquadJS, pull requests merged in 2021-04, with the labels that each got.

#187 Fix layer information link
  squad-server/layers/layers.js
Labels: core bug, patch

#188 Add support for multiple servers to discord-base-message-updater plugin
  squad-server/plugins/discord-base-message-updater.js
Labels: patch, plugin bug

#189 Add FogOfWar plugin
  README.md
  config.json
  squad-server/plugins/fog-of-war.js
  squad-server/rcon.js
Labels: minor, plugin feature request

#190 Fix player connection event.
  squad-server/log-parser/steamid-connected.js
Labels: core bug, patch

#191 Fix player disconnection event.
  squad-server/log-parser/player-disconnected.js
Labels: core bug, patch
