Repository Team-Silver-Sphere/SquadJS, pull requests merged in 2023-11, with the labels that each got.

#261 Do Not Log Password in RCON unless Logger verbosity is 4
  core/rcon.js
Labels: core bug, minor

#288 Add a PLAYER_LEFT event
  squad-server/log-parser/player-disconnected.js
Labels: core bug, minor

#308 Update package.json
  package.json
Labels: patch

#310 Update player-disconnected.js - Fixing a broken bracket
  squad-server/log-parser/player-disconnected.js
Labels: core bug, patch

#312 Track playercontrollers for death logging
  squad-server/index.js
Labels: core bug, patch

#313 Added additional properties to getListPlayers and getSquads methods
  squad-server/rcon.js
Labels: core bug, patch

#322 Fix typo in auto-kick-unassigned.js
  squad-server/plugins/auto-kick-unassigned.js
Labels: patch

#324 Adds Support for #322
  README.md
  config.json
  squad-server/log-parser/player-disconnected.js
  squad-server/rcon.js
Labels: patch

#325 Update package.json to 3.8.2
  package.json
Labels: patch
