Repository Team-Silver-Sphere/SquadJS, pull requests merged in 2024-08, with the labels that each got.

#350 The quick and easy Discord.js upgrade
  squad-server/factory.js
  squad-server/package.json
  squad-server/plugins/discord-base-message-updater.js
  squad-server/plugins/discord-base-plugin.js
  squad-server/plugins/discord-placeholder.js
  squad-server/plugins/discord-rcon.js
  squad-server/plugins/discord-server-status.js
  squad-server/plugins/discord-subsystem-restarter.js
Labels: core bug, plugin bug, minor, Testing Required

#371 fix: eosID not saved to database on connect
  squad-server/plugins/db-log.js
Labels: core bug, patch

#375 Update ftp-tail to fix SFTP tailing issue
  core/package.json
Labels: core bug, patch

#376 fix: match other disconnect logs except without eosID
  squad-server/log-parser/player-disconnected.js
Labels: core bug, patch

#363 fix: update the server layer extraction
  squad-server/index.js
  squad-server/layers/layers.js
  squad-server/rcon.js
Labels: core bug, patch

#379 Added FTP source type to admin lists.
  README.md
  config.json
  squad-server/factory.js
  squad-server/package.json
  squad-server/plugins/discord-base-plugin.js
  squad-server/plugins/discord-server-status.js
  squad-server/templates/readme-template.md
  squad-server/utils/admin-lists.js
  squad-server/utils/writable-buffer.js
Labels: core bug, chore

#382 Moving Squad Images off of CDN
  README.md
  config.json
  squad-server/plugins/discord-server-status.js
Labels: core bug, chore
