Repository Team-Silver-Sphere/SquadJS, pull requests merged in 2024-01, with the labels that each got.

#318 EOS integration
  core/log-parser/index.js
  core/rcon.js
  package.json
  squad-server/index.js
  squad-server/log-parser/adding-client-connection.js
  squad-server/log-parser/check-permission-resolve-eosid.js
  squad-server/log-parser/client-external-account-info.js
  squad-server/log-parser/client-login.js
  squad-server/log-parser/index.js
  squad-server/log-parser/join-request.js
  squad-server/log-parser/login-request.js
  squad-server/log-parser/pending-connection-destroyed.js
  squad-server/log-parser/player-connected.js
  squad-server/log-parser/player-damaged.js
  squad-server/log-parser/player-died.js
  squad-server/log-parser/player-disconnected.js
  squad-server/log-parser/player-join-succeeded.js
  squad-server/log-parser/player-possess.js
  squad-server/log-parser/player-revived.js
  squad-server/log-parser/player-un-possess.js
  squad-server/log-parser/player-wounded.js
  squad-server/log-parser/playercontroller-connected.js
  squad-server/log-parser/sending-auth-result.js
  squad-server/plugins/db-log.js
  squad-server/rcon.js
Labels: core bug, core feature request, major

#336 Removing CDN link for new versioning.
  squad-server/utils/print-logo.js
Labels: core bug, patch

#337 Patching to 4.0.1
  package.json
Labels: patch

#319 Updated Factory.js to ignore non .js file types
  squad-server/factory.js
Labels: core bug, patch

#341 Rollback on commit
  squad-server/factory.js
Labels: core bug
